### PR TITLE
fix: img with missing alt should have role img

### LINKED ISSUE #429: img elements with no alt attribute should maintain a role of img
Currently, `getRole` on an image that is missing an `alt` attribute returns `null`. this is incorrect.

given the following markup:

```js
const imgEl = (new JSDOM(<img src='logo.png"'>`)).window.document.body.querySelector('img')
```

`getRole(imgEl)` should return `img`, but instead it returns `null`. (when adding an `alt` attribute, `getRole` return `img` correctly).

A completely missing `alt` attribute is notably different from `alt=""` or simply `alt`;  adding an `alt` attribute with an empty value _should_ remove the node from the AOM, whereas omitting it should _not_. using an empty value is a way for authors to instruct the browser to ignore an image.

Confirmed the above expected behavior in Chrome.

[related to #428]

### PR DESCRIPTION
**Pull request by ckundo**
- browsers will treat an image with missing alt as an image.
- null alt is different than empty string: empty string removes the node from the AOM, where missing (null) alt does not.
- this change may impact tests that incorrectly rely on missing alt and `alt=''` being equivalent.
- recommend a patch level release.

[fixes #429]

### CODE REVIEW

File: sources/__tests__/getRole.js [hunk 1]
```diff
@@ -89,6 +89,7 @@ const cases = [
 	["html", null, createElementFactory("html", {})],
 	["iframe", null, createElementFactory("iframe", {})],
 	["img with alt=\"some text\"", "img", createElementFactory("img", {alt: "text"})],
+	["img with missing alt", "img", createElementFactory("img", {})],
```
Comment (ckundo) [inline sources/__tests__/getRole.js:92]: per discussion https://github.com/eps1lon/dom-accessibility-api/issues/429#issuecomment-696259998 I think we agree on this behavior @eps1lon?

Comment (eps1lon) [reply sources/__tests__/getRole.js:92]: Perfect, thanks!

**Review by eps1lon — COMMENTED** [review]
You need to wrap the case in a block statement to avoid misleading block scoping:

`case "img": { /* your code */ }`

File: .changeset/light-ladybugs-destroy.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"dom-accessibility-api": patch
+---
+
+Maintain img role for img with missing alt attribute.
```
Comment (ckundo) [inline .changeset/light-ladybugs-destroy.md:5]: added this due to build guidance... do you want it here?

**Comment by eps1lon** [comment]
@ckundo Much appreciated, thanks!
