### PR TITLE
fix: determine accname for elements with slots

### LINKED ISSUE #423: Accessible name incorrect when <slot> involved
I want to use this package to determine the accessible name of an element containing a slot (or when the node used to determine accessible name contains a slot, e.g. with aria-labelledby). Currently `computeAccessibleName` does not return the same accessible name the browser uses when called on an element containing a slot. I've created [a GitHub repo demonstrating the issue](https://github.com/geoffrich/accname-slot-demo).

The demo creates two custom elements, each containing a button with a slot. The second element (custom-button-with-default) sets a default value for the slot, while the first (custom-button) does not. The test code invokes `computeAccessibleName` on the `<button>` within each custom element's shadow root.

The test cases are as follows:
- When called on the button within `custom-button`, this package returns an empty string while Firefox/Chrome determines the accessible name to be "Custom name"
- When called on the button within the first `custom-button-with-default` (slot content is set), this package returns "Default name" while Firefox/Chrome determines the accessible name to be "Custom name"
- When called on the button within the second `custom-button-with-default` (slot content is not set), this package returns "Default name" while Firefox/Chrome determine the accessible name to be "Default name"

Below is an image how Firefox displays the accessibility tree. You can also clone and run my demo locally.
Image of accessibility tree from demo page in firefox

This is an interesting one, since I couldn't find a corresponding WPT and the spec doesn't cover this. I have [an issue out on the accessible name spec to clarify this](https://github.com/w3c/accname/issues/93). Either way, there does seem to be a mismatch between how this package determines the accessible name and how browsers do (at least Chrome and Firefox, I'm not able to test Safari).

The root cause of the issue seems to be related to how slots work. The "Custom name" text passed to the custom-button does not become a child node of the slot, but rather an assigned node. This package (and the spec) only consider child nodes. 

```js
const slot = document.querySelector('custom-button').shadowRoot.querySelector('slot')
console.log(slot.childNodes)        // NodeList []
console.log(slot.assignedNodes())   // Array [ #text "Custom name" ]
```

To accurately determine the accessible name with slotted content, assigned nodes should be considered as well as child nodes. We'd also need to be careful of [the case where default content is provided to the slot](https://github.com/w3c/accname/issues/93#issuecomment-689871535).

I'd be happy to take a crack at implementing this if you agree that it's an issue.

### PR DESCRIPTION
**Pull request by geoffrich**
Correctly determine accessible name when element contains a slot.

Previously, computing the accessible name would only examine child nodes. However, content placed in a slot is is an assigned node, not a child node. If an element is a slot, we now examine either assignedNodes (if content was placed in the slot) or childNodes (the default content of the slot).

Fixes #423

### CODE REVIEW

File: sources/__tests__/accessible-name.js [hunk 1]
```diff
@@ -191,6 +200,52 @@ describe("to upstream", () => {
...
+			}
+		);
+
+		customElements.define(
+			"custom-button-with-default",
+			class extends HTMLElement {
+				constructor() {
+					super();
+					const shadowRoot = this.attachShadow({ mode: "open" });
+					shadowRoot.innerHTML = `<button data-test><slot>Default name</slot></button>`;
```
Comment (eps1lon) [inline sources/__tests__/accessible-name.js:222]: Should this `data-test` attribute be here? I guess it's harmless right now but might be confusing if an actual test forgets to add a `data-test` attribute.

File: sources/accessible-name-and-description.ts [hunk 2]
```diff
@@ -306,11 +307,27 @@ function getLabels(element: Element): HTMLLabelElement[] | null {
...
 }
 
+/**
+ * Gets the contents of a slot used for computing the accname
+ * @param slot
+ */
+function getSlotContents(slot: HTMLSlotElement): Node[] {
+	// Computing the accessible name for elements containing slots
+	// is not currently defined in the spec. This implementation
+	// reflects current browser behavior.
```
Comment (eps1lon) [inline sources/accessible-name-and-description.ts:317]: nit: With what browser did you verify the changes? I guess Chrome but for future changes it'd be nice to have this reference. Especially if browser behavior changes.

**Review by eps1lon — CHANGES_REQUESTED** [review]
Looks great! Appreciate the work. I just have some editorial nitpicks/questions.

File: sources/accessible-name-and-description.ts (hunk 2 above)
Comment (geoffrich) [reply sources/accessible-name-and-description.ts:317]: I tested Firefox/NVDA and iOS Safari/VoiceOver. I'll update the comment with the browser/SR combos and versions.

File: sources/__tests__/accessible-name.js (hunk 1 above)
Comment (geoffrich) [reply sources/__tests__/accessible-name.js:222]: This is for the `testShadowDomMarkup` function, which queries for an element in the shadowRoot with the data-test attribute. Is there another way you'd prefer to identify the element under test?

Comment (eps1lon) [reply sources/__tests__/accessible-name.js:222]: Is this actually how a screen reader works? The idea for `data-test` was that that would be the element for which a screen reader is determining the accessible name. 

In other words: Say I have a `CustomButton` for which I write test: How would I query for the element for which I want the accessible name? You wouldn't put `data-test` inside the implementation but rather `<custom-button data-test />` and compute the accessible name for that.

Comment (eps1lon) [reply sources/__tests__/accessible-name.js:222]: So I guess this all makes sense (barely any ShadowDOM knowledge). My main issue is that `testShadoDOMMarkup` is tied to the custom elements inside the `"slots"` block. If you could move `testShadowDOMMarkup` inside the same block then we're probably not leaking implementation details.

My concern is not with the current tests but how these evolve over time. From my experience test utilities get oftentimes abused so we need to make sure they're scoped to their actual usage when introduced.

Comment (geoffrich) [reply sources/__tests__/accessible-name.js:222]: I think there's some confusion as to which element's name we're determining. We're not determining the name of `<custom-button>`, but the `<button>` inside of `<custom-button>`. Semantically, `<custom-button>` is equivalent to a `<span>` -- it has no special meaning to assistive tech. So, that's why I put `data-test` on the inner `<button>` -- that's the element under test.

I think re-using the `data-test` is confusing because it implies that the `<custom-button>` is under test. What do you think about introducing a `data-root` attribute to query for the custom element container and leaving `data-test` on the `<button>` we're actually testing?

So our test fixture would be
```html
<custom-button data-root></custom-button>
```

And our test helper would be:
```diff
function testShadowDomMarkup(markup, accessibleName) {
	const container = renderIntoDocument(markup);

	const testNode = container
-		.querySelector("[data-test]")
+		.querySelector("[data-root]")
		.shadowRoot.querySelector("[data-test]");
	expect(testNode).toHaveAccessibleName(accessibleName);
}

Comment (eps1lon) [reply sources/__tests__/accessible-name.js:222]: > <custom-button data-root></custom-button>

That makes the most sense to me :+1:

File: sources/accessible-name-and-description.ts (hunk 2 above)
Comment (geoffrich) [reply sources/accessible-name-and-description.ts]: Code comment has been updated with the above. Please resolve if you're satisfied with the change.

File: sources/__tests__/accessible-name.js (hunk 1 above)
Comment (geoffrich) [reply sources/__tests__/accessible-name.js:222]: Tests have been updated to use `data-root` on the custom element containing the element under test. Please resolve if you're satisfied with the change.

**Review by eps1lon — APPROVED** [review]

**Comment by eps1lon** [comment]
I'll release it over the course of this week while I setup automated releases.
